//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FigureCalculator.Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IFigureCalculator")]
    internal interface IFigureCalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFigureCalculator/GetCircleLength", ReplyAction="http://tempuri.org/IFigureCalculator/GetCircleLengthResponse")]
        double GetCircleLength(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFigureCalculator/GetCircleLength", ReplyAction="http://tempuri.org/IFigureCalculator/GetCircleLengthResponse")]
        System.Threading.Tasks.Task<double> GetCircleLengthAsync(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFigureCalculator/GetCircleArea", ReplyAction="http://tempuri.org/IFigureCalculator/GetCircleAreaResponse")]
        double GetCircleArea(double radius);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFigureCalculator/GetCircleArea", ReplyAction="http://tempuri.org/IFigureCalculator/GetCircleAreaResponse")]
        System.Threading.Tasks.Task<double> GetCircleAreaAsync(double radius);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IFigureCalculatorChannel : FigureCalculator.Client.Service.IFigureCalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class FigureCalculatorClient : System.ServiceModel.ClientBase<FigureCalculator.Client.Service.IFigureCalculator>, FigureCalculator.Client.Service.IFigureCalculator {
        
        public FigureCalculatorClient() {
        }
        
        public FigureCalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FigureCalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FigureCalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FigureCalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetCircleLength(double radius) {
            return base.Channel.GetCircleLength(radius);
        }
        
        public System.Threading.Tasks.Task<double> GetCircleLengthAsync(double radius) {
            return base.Channel.GetCircleLengthAsync(radius);
        }
        
        public double GetCircleArea(double radius) {
            return base.Channel.GetCircleArea(radius);
        }
        
        public System.Threading.Tasks.Task<double> GetCircleAreaAsync(double radius) {
            return base.Channel.GetCircleAreaAsync(radius);
        }
    }
}
